### ISSUE TITLE
circles not showing

### ISSUE THREAD

**Issue by Kame7C0** [kidscancode/circle_jump#1]
Godot 3.1.1 Win7 x64 Intel(R) HD Graphics 500

for some reson calling "update()" in "Circle.gd" hides the circles.
24eb3cb919f16fb99e498f6964c76baf5a6e79f1 without any modification
![no_modification](https://user-images.githubusercontent.com/3462746/56919236-01e7b580-6ab8-11e9-866e-058ba443e9df.gif)
with commented "update()" on line 40
![without_update](https://user-images.githubusercontent.com/3462746/56919241-07450000-6ab8-11e9-86b2-e4586d41fadd.gif)

**Comment by cbscribe** [comment]
Well, that's a really strange issue. I wonder if it's driver-related. I am unable to replicate on any device I have. Can you try changing to GLES2?

**Comment by Kame7C0** [comment]
yep using GLES2 is a fix

**Comment by cbscribe** [comment]
Nice - thanks for testing. That means it's definitely a driver support issue. I'm leaning towards switching the project to GLES2.

**Comment by cbscribe** [comment]
Closed in 07b17ad
