### ISSUE TITLE
What do you think about renaming repository to 'game' instead of 'tutorial'? :)

### ISSUE THREAD

**Issue by pywkm** [kidscancode/circle_jump#8]
Hi,
first of all, thank you for the great tutorial showing the creation of this game. It was probably the first time I followed a series of videos from first to last in two days and wrote the entire code along with the host, not copying a bit from his repo. :) It was well made, fun, and very informative. For someone like me (with Python background) this is perfectly prepared content to dive into Godot Engine right away. Thank you!

Now, to the point. The next step for me was to find more resources for Godot and I stepped into [awesome-godot](https://github.com/Calinou/awesome-godot) repository and was a little surprised that `Circle Jump` isn't listed there under 2D games. This repository here, after all, is in fact repo for a fully functional, quite original, and enjoyable game. Published on Play store. I was in the middle of editing their `README.md` when I realized that your repository's description and readme are saying that this is tutorial. You don't even include the screenshot/preview from the latest version of the game, only the prototype presented in the very first video. :) What do you think about rewording description and readme files so they call it a game? With the links to the tutorial where it was created, of course. I think it's the main reason, this repo isn't listed there under the Games section. And sometimes people are looking on the curated lists of that kind for games before they dive into the tutorials section (where you are listed of course), just to see what given language/framework is capable of, if it is worth learning. ;)

You could, for instance, tag the latest commit as `tutorial-part-14` and point to that commit/branch in your Youtube video description - in case the development of the game moves forward and doesn't match state from the last video. Just a thought if that is your main concern. :)

Wiktor

**Comment by cbscribe** [comment]
Thanks for the comments. I've updated the descriptions a bit.

I don't really have anything to do with awesome-godot, but you're welcome to submit it over there and get it listed. :)
